/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

function parse(code: string, allowReturnOutsideFunction: boolean, jsx: boolean): Buffer
function parseAsync(code: string, allowReturnOutsideFunction: boolean, jsx: boolean, signal?: AbortSignal | undefined | null): Promise<Buffer>
function xxhashBase64Url(input: Uint8Array): string
function xxhashBase36(input: Uint8Array): string
function xxhashBase16(input: Uint8Array): string
